/* @LOADING-ACTIONS */
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

/* @AUTH-ACTIONS */
export const AUTH = "AUTH";

/* @PRODUCT-ACTIONS */
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT";

/* @CART-ACTIONS */
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_RESET = "CART_RESET";
