/* @LOADING-ACTIONS */
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

/* @AUTH-ACTIONS */
export const AUTH = "AUTH";
export const GET_USER_BY_ACCESS_TOKEN = "GET_USER_BY_ACCESS_TOKEN";
export const LOGOUT = "LOGOUT";

/* @PRODUCT-ACTIONS */
export const FETCH_ALL_PRODUCTS_BY_CATEGORY = "FETCH_ALL_PRODUCTS_BY_CATEGORY";
export const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT";

/* @CART-ACTIONS */
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_RESET = "CART_RESET";

/* @SELLER-ACTIONS */
export const FETCH_ALL_SELLERS = "FETCH_ALL_SELLERS";

/* @CATEGORIES-ACTIONS */
export const FETCH_ALL_CATEGORIES = "FETCH_ALL_CATEGORIES";
